import type { Assignment, User } from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "Alex Doe",
  email: "alex@example.com",
  avatarUrl: "https://placehold.co/100x100.png",
  rating: 4.8,
  reviewsCount: 32,
};

export const mockAssignments: Assignment[] = [
  {
    id: "1",
    title: "Complete Physics Lab Report",
    description: "Detailed lab report on the principles of thermodynamics. Must include graphs and data analysis. The report should be at least 10 pages long and follow the university's formatting guidelines.",
    amount: 1500,
    deadline: new Date("2024-08-15"),
    status: "Open",
    requester: { ...mockUser, id: "user-2", name: "Jane Smith" },
    location: "Mumbai, Maharashtra",
  },
  {
    id: "2",
    title: "Write an Essay on Ancient History",
    description: "A 2000-word essay on the impact of the Roman Empire on modern law. Requires at least 5 academic sources.",
    amount: 2500,
    deadline: new Date("2024-08-20"),
    status: "In Progress",
    requester: { ...mockUser, id: "user-3", name: "Robert Brown" },
    provider: mockUser,
    location: "Delhi, NCR",
  },
  {
    id: "3",
    title: "Create a Presentation on Marketing",
    description: "A 20-slide presentation for a business class on digital marketing strategies for startups.",
    amount: 1200,
    deadline: new Date("2024-07-30"),
    status: "Completed",
    requester: mockUser,
    provider: { ...mockUser, id: "user-4", name: "Emily White" },
    location: "Bengaluru, Karnataka",
  },
    {
    id: "4",
    title: "Solve Calculus Problem Set",
    description: "Problem set covering differentiation and integration. 15 problems in total, need to show all steps for each solution.",
    amount: 1800,
    deadline: new Date("2024-09-01"),
    status: "Open",
    requester: { ...mockUser, id: "user-5", name: "Michael Green" },
    location: "Pune, Maharashtra",
  },
   {
    id: "5",
    title: "Develop a Python Script for Data Scraping",
    description: "A script to scrape data from a list of websites and store it in a CSV file. The script should be well-documented.",
    amount: 3000,
    deadline: new Date("2024-08-25"),
    status: "Open",
    requester: { ...mockUser, id: "user-6", name: "Sarah Black" },
    location: "Hyderabad, Telangana",
  },
  {
    id: "6",
    title: "Design a Logo for a New App",
    description: "Create a modern and minimalist logo for a new mobile application. Deliverables should include vector files.",
    amount: 4000,
    deadline: new Date("2024-09-05"),
    status: "Open",
    requester: { ...mockUser, id: "user-7", name: "Chris Pine" },
    location: "Chennai, Tamil Nadu",
  },
];
